####################################
# Alacritty Configuration
####################################

[window]
opacity = 0.8
blur = true
decorations = "Buttonless"
startup_mode = "Windowed"
dimensions = { columns = 120, lines = 30 }

[window.padding]
x = 8
y = 6

####################################
# Font
####################################
[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"

####################################
# Cursor
####################################
[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 500

####################################
# Colors
####################################
[colors.primary]
foreground = "#d6d6d6"
background = "#111111"

[colors.cursor]
text = "#111111"
cursor = "#f5c2e7"

[colors.selection]
text = "#f8f8f2"
background = "#44475a"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#cdd6f4"

[colors.bright]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#f5f5f5"

####################################
# Mouse
####################################
[mouse]
hide_when_typing = true

####################################
# Keyboard
####################################
[keyboard]
bindings = [
  { key = "Key1", mods = "Control", action = "SelectTab1" },
  { key = "Key2", mods = "Control", action = "SelectTab2" },
  { key = "Key3", mods = "Control", action = "SelectTab3" },
  { key = "Key4", mods = "Control", action = "SelectTab4" },
  { key = "Key5", mods = "Control", action = "SelectTab5" },
  { key = "Key6", mods = "Control", action = "SelectTab6" },
  { key = "Key7", mods = "Control", action = "SelectTab7" },
  { key = "Key8", mods = "Control", action = "SelectTab8" },
  { key = "Key9", mods = "Control", action = "SelectTab9" },
]
