"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$directory
$hostname$character"""

right_format = """$nix_shell$rust$golang$nodejs$c$cpp$git_branch$git_status"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[directory]
style = "bold cyan dimmed"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "../"
read_only = " "

# --- Git Branch ---
[git_branch]
symbol = "" # " "
only_attached = true
format = "[$symbol$branch]($style) "
style = "bold purple dimmed"

# --- Git Status (symbols, no emojis) ---
[git_status]
disabled = false
format = "$conflicted$staged$modified$renamed$deleted$untracked$ahead_behind"

conflicted = "[!!${count}](bold red) "
staged     = "[+${count}](bold green) "
modified   = "[!${count}](bold yellow) "
renamed    = "[>${count}](cyan) "
deleted    = "[-${count}](red) "
untracked  = "[?${count}](blue) "

ahead      = "[↑${count}](bold green) "
behind     = "[↓${count}](bold red) "
diverged   = "[↕${ahead_count}/${behind_count}](magenta) "
stashed    = "[s${count}](white) "

style = ""

[nix_shell]
symbol = "󱄅 "
format = "[$symbol]($style) "
style = "bold blue dimmed"

[python]
symbol = " "
format = "[ $version]($style) "
style = "yellow dimmed"

[rust]
symbol = " "
format = "[$symbol]($style) "
style = "bold red"

[golang]
symbol = " "
format = "[$symbol]($style) "
style = "bold cyan"

[nodejs]
symbol = " "
format = "[$symbol]($style) "
style = "bold green"

[c]
symbol = " "
format = "[$symbol]($style) "
style = "bold blue"

[cpp]
symbol = "󰙲 "
format = "[$symbol]($style) "
style = "bold blue"

[jobs]
symbol = "✦"
format = "[✦]($style) "
style = "blue italic"

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold blue"

[time]
disabled = true

